{
 "title": "Indoor sound classification",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "device_id",
    "query": {
     "query": "label_values(indoor_sound_classification_prediction, device_id)"
    }
   },
   {
    "name": "tag",
    "label": "tag",
    "query": {
     "query": "label_values(indoor_sound_classification_prediction, tag)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$device_id", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "device_id" },
  {
   "title": "Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Prediction (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Prediction (max)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "clamp(topk(1, indoor_sound_classification_prediction{device_id=\"$device_id\"}), 0, 0.001) * 1000",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Prediction (current max)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 16, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, indoor_sound_classification_prediction{device_id=\"$device_id\"})",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Prediction (hourly heatmap)",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 22, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "sum(indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction (Status timeline)",
   "type": "state-timeline",
   "gridPos": { "h": 12, "w": 16, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"} > 0.3",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "Prediction (week x month)",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum(count_over_time((indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"} > 0.3)[$__rate_interval:15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction (hour x day)",
   "type": "neocat-cal-heatmap-panel",
   "gridPos": { "h": 25, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(count_over_time((indoor_sound_classification_prediction{device_id=\"$device_id\", tag=~\"$tag\"} > 0.3)[$__rate_interval:15s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prediction (topk bar chart)",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "topk(10, indoor_sound_classification_prediction{device_id=\"$device_id\"})",
     "legendFormat": "{{tag}}"
    }
   ]
  }
 ]
}